import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const inter = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "500", "700", "900"],
});

export const metadata = {
  title: "afyatips",
  description: "Generated by kayCom inc",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className} layout="true">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
